<a href="https://colab.research.google.com/github/Olga13579/Data_Circle_Project-Stack_Overflow/blob/uniqe-db/Data_Circle_Project_Stack_Overflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
base = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/{}/results.csv"


df_2022 = pd.read_csv(base.format(2022))
df_2023 = pd.read_csv(base.format(2023))
df_2024 = pd.read_csv(base.format(2024))
df_2025 = pd.read_csv(base.format(2025))


#with pd.option_context("display.max_rows", None):
      #print(df_2025.isnull().sum())
#print(df_2024.shape)
#df_2025.head()

/tmp/ipykernel_822/2156327715.py:7: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025 = pd.read_csv(base.format(2025))

In [22]:
cols_2022 = set(df_2022.columns)
cols_2023 = set(df_2023.columns)
cols_2024 = set(df_2024.columns)
cols_2025 = set(df_2025.columns)

common_cols = (cols_2022) & (cols_2023) & (cols_2024) & (cols_2025)

cols = sorted(common_cols)

In [23]:
small_2022 = df_2022[cols].copy()
small_2022["Year"] = 2022

small_2023 = df_2023[cols].copy()
small_2023["Year"] = 2023

small_2024 = df_2024[cols].copy()
small_2024["Year"] = 2024

small_2025 = df_2025[cols].copy()
small_2025["Year"] = 2025



df = pd.concat([small_2022, small_2023, small_2024, small_2025], ignore_index = True)

print(df[df['MainBranch'] == 'I am learning to code'].isnull().sum())

print(df.info())

Age                                 103
CompTotal                         17202
ConvertedCompYearly               17367
Country                            1670
Currency                          16177
DatabaseHaveWorkedWith             7238
DatabaseWantToWorkWith             9332
DevType                            8116
EdLevel                             733
Employment                          130
ICorPM                            16325
LanguageHaveWorkedWith             2823
LanguageWantToWorkWith             3852
LearnCode                          1147
MainBranch                            0
OfficeStackAsyncHaveWorkedWith    10567
OfficeStackAsyncWantToWorkWith    12303
OpSysPersonal use                  2615
OpSysProfessional use              6147
OrgSize                           17132
PlatformHaveWorkedWith             9990
PlatformWantToWorkWith            11693
PurchaseInfluence                 17056
RemoteWork                        13792
ResponseId                            0
SOAccount                          2141
SOComm                             2305
SOPartFreq                         6806
SOVisitFreq                        2648
WebframeHaveWorkedWith             8024
WebframeWantToWorkWith             9615
WorkExp                           15907
YearsCode                          1532
Year                                  0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277080 entries, 0 to 277079
Data columns (total 34 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Age                             274758 non-null  object
 1   CompTotal                       145253 non-null  float64
 2   ConvertedCompYearly             133472 non-null  float64
 3   Country                         254111 non-null  object
 4   Currency                        198719 non-null  object
 5   DatabaseHaveWorkedWith          209360 non-null  object
 6   DatabaseWantToWorkWith          174216 non-null  object
 7   DevType                         241299 non-null  object
 8   EdLevel                         268477 non-null  object
 9   Employment                      273383 non-null  object
 10  ICorPM                          142995 non-null  object
 11  LanguageHaveWorkedWith          249531 non-null  object
 12  LanguageWantToWorkWith          230567 non-null  object
 13  LearnCode                       253287 non-null  object
 14  MainBranch                      277080 non-null  object
 15  OfficeStackAsyncHaveWorkedWith  193264 non-null  object
 16  OfficeStackAsyncWantToWorkWith  147987 non-null  object
 17  OpSysPersonal use               247111 non-null  object
 18  OpSysProfessional use           225946 non-null  object
 19  OrgSize                         197740 non-null  object
 20  PlatformHaveWorkedWith          180176 non-null  object
 21  PlatformWantToWorkWith          145670 non-null  object
 22  PurchaseInfluence               200776 non-null  object
 23  RemoteWork                      221354 non-null  object
 24  ResponseId                      277080 non-null  int64
 25  SOAccount                       251781 non-null  object
 26  SOComm                          249969 non-null  object
 27  SOPartFreq                      201755 non-null  object
 28  SOVisitFreq                     250347 non-null  object
 29  WebframeHaveWorkedWith          188635 non-null  object
 30  WebframeWantToWorkWith          159037 non-null  object
 31  WorkExp                         152899 non-null  float64
 32  YearsCode                       261677 non-null  object
 33  Year                            277080 non-null  int64
dtypes: float64(3), int64(2), object(29)
memory usage: 71.9+ MB
None

In [34]:
# Data base uniqe

array_db=df['DatabaseHaveWorkedWith'].unique()

unique_db_hw = (
    pd.Series(array_db)
    .dropna()
    .str.split(';')
    .explode()
    .str.strip()
    .unique()
)

print(unique_db_hw)

['Microsoft SQL Server' 'Cloud Firestore' 'Elasticsearch'
 'Firebase Realtime Database' 'MongoDB' 'MySQL' 'Couchbase' 'CouchDB'
 'PostgreSQL' 'Redis' 'DynamoDB' 'Neo4j' 'SQLite' 'Cassandra' 'MariaDB'
 'Oracle' 'IBM DB2' 'Supabase' 'BigQuery' 'Dynamodb' 'Cosmos DB' 'H2'
 'Datomic' 'InfluxDB' 'Microsoft Access' 'Firebird' 'Solr' 'Cockroachdb'
 'Snowflake' 'Couch DB' 'RavenDB' 'Neo4J' 'Clickhouse' 'DuckDB' 'TiDB'
 'Presto' 'Databricks SQL' 'EventStoreDB' 'Amazon Redshift' 'Pocketbase'
 'Valkey']

In [39]:
df['YearsCode'].unique()

array([nan, '14', '20', '8', '15', '3', '1', '6', '37', '5', '12', '22',
       '11', '4', '7', '13', '36', '2', '25', '10', '40', '16', '27',
       '24', '19', '9', '17', '18', '26', 'More than 50 years', '29',
       '30', '32', 'Less than 1 year', '48', '45', '38', '39', '28', '23',
       '43', '21', '41', '35', '50', '33', '31', '34', '46', '44', '42',
       '47', '49', 14.0, 10.0, 12.0, 5.0, 22.0, 20.0, 13.0, 30.0, 15.0,
       9.0, 6.0, 3.0, 40.0, 8.0, 45.0, 35.0, 11.0, 7.0, 47.0, 41.0, 36.0,
       23.0, 29.0, 26.0, 25.0, 38.0, 21.0, 19.0, 18.0, 16.0, 4.0, 17.0,
       42.0, 27.0, 24.0, 2.0, 28.0, 37.0, 32.0, 1.0, 39.0, 53.0, 33.0,
       50.0, 48.0, 44.0, 31.0, 46.0, 43.0, 49.0, 52.0, 34.0, 51.0, 58.0,
       57.0, 54.0, 63.0, 60.0, 55.0, 65.0, 100.0, 99.0, 56.0, 69.0, 90.0,
       61.0, 67.0, 75.0, 64.0, 98.0, 68.0, 89.0, 62.0, 78.0, 70.0, 76.0,
       82.0, 59.0], dtype=object)

In [43]:
df[df['YearsCode'] == 'Less than 1 year'].count()

Age                               2930
CompTotal                          210
ConvertedCompYearly                191
Country                           2936
Currency                           388
DatabaseHaveWorkedWith            1406
DatabaseWantToWorkWith            1072
DevType                           1789
EdLevel                           2947
Employment                        2945
ICorPM                             447
LanguageHaveWorkedWith            2443
LanguageWantToWorkWith            2165
LearnCode                         2942
MainBranch                        2950
OfficeStackAsyncHaveWorkedWith    1045
OfficeStackAsyncWantToWorkWith     761
OpSysPersonal use                 2664
OpSysProfessional use             1950
OrgSize                            388
PlatformHaveWorkedWith            1072
PlatformWantToWorkWith             780
PurchaseInfluence                  387
RemoteWork                        1026
ResponseId                        2950
SOAccount                         2813
SOComm                            2801
SOPartFreq                        1757
SOVisitFreq                       2520
WebframeHaveWorkedWith            1316
WebframeWantToWorkWith            1045
WorkExp                            385
YearsCode                         2950
Year                              2950
dtype: int64

In [ ]:
df['YearsCode'].unique()

array([nan, '14', '20', '8', '15', '3', '1', '6', '37', '5', '12', '22',
       '11', '4', '7', '13', '36', '2', '25', '10', '40', '16', '27',
       '24', '19', '9', '17', '18', '26', 'More than 50 years', '29',
       '30', '32', 'Less than 1 year', '48', '45', '38', '39', '28', '23',
       '43', '21', '41', '35', '50', '33', '31', '34', '46', '44', '42',
       '47', '49', 14.0, 10.0, 12.0, 5.0, 22.0, 20.0, 13.0, 30.0, 15.0,
       9.0, 6.0, 3.0, 40.0, 8.0, 45.0, 35.0, 11.0, 7.0, 47.0, 41.0, 36.0,
       23.0, 29.0, 26.0, 25.0, 38.0, 21.0, 19.0, 18.0, 16.0, 4.0, 17.0,
       42.0, 27.0, 24.0, 2.0, 28.0, 37.0, 32.0, 1.0, 39.0, 53.0, 33.0,
       50.0, 48.0, 44.0, 31.0, 46.0, 43.0, 49.0, 52.0, 34.0, 51.0, 58.0,
       57.0, 54.0, 63.0, 60.0, 55.0, 65.0, 100.0, 99.0, 56.0, 69.0, 90.0,
       61.0, 67.0, 75.0, 64.0, 98.0, 68.0, 89.0, 62.0, 78.0, 70.0, 76.0,
       82.0, 59.0], dtype=object)

In [38]:
df.groupby('ResponseId').agg({'Year': 'count'})

            Year
ResponseId
1              4
2              4
3              4
4              4
5              4
...          ...
89180          1
89181          1
89182          1
89183          1
89184          1

[89184 rows x 1 columns]