<a href="https://colab.research.google.com/github/Olga13579/Data_Circle_Project-Stack_Overflow/blob/feature%2Floading-pershina/notebooks/01_loading_pershina.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
base = "https://github.com/StackExchange/Survey/raw/refs/heads/main/packages/archive/{}/results.csv"

In [4]:
df_2022 = pd.read_csv(base.format(2022))
print(df_2022.shape)
df_2022.head()

(73268, 79)

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [5]:
df_2023 = pd.read_csv(base.format(2023))
print(df_2023.shape)
df_2023.head()

(89184, 84)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,...,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,...,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,...,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0

In [6]:
df_2024 = pd.read_csv(base.format(2024))
print(df_2024.shape)
df_2024.head()

(65437, 114)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [7]:
df_2025 = pd.read_csv(base.format(2025))
print(df_2025.shape)
df_2025.head()

/tmp/ipykernel_1692/1779289391.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2025 = pd.read_csv(base.format(2025))

(49191, 172)

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [8]:
df_2022.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'Country', 'Currency',
       'CompTotal', 'CompFreq', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysProfessional use',
       'OpSysPersonal use', 'VersionControlSystem', 'VCInteraction',
       'VCHostingPersonal use', 'VCHostingProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackSyncHaveWorkedWith', 'OfficeStackSyncWantToWorkWith',
       'Blockchain', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'Age', 'Gender', 'Trans', 'Sexuality', 'Ethnicity',
       'Accessibility', 'MentalHealth', 'TBranch', 'ICorPM', 'WorkExp',
       'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Onboarding', 'ProfessionalTech', 'TrueFalse_1', 'TrueFalse_2',
       'TrueFalse_3', 'SurveyLength', 'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [9]:
df_2023.columns

Index(['ResponseId', 'Q120', 'MainBranch', 'Age', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'TechList', 'BuyNewTool', 'Country',
       'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysPersonal use',
       'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith',
       'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'AISearchHaveWorkedWith',
       'AISearchWantToWorkWith', 'AIDevHaveWorkedWith', 'AIDevWantToWorkWith',
       'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOComm',
       'SOAI', 'AISelect', 'AISent', 'AIAcc', 'AIBen',
       'AIToolInterested in Using', 'AIToolCurrently Using',
       'AIToolNot interested in Using', 'AINextVery different',
       'AINextNeither different nor similar', 'AINextSomewhat similar',
       'AINextVery similar', 'AINextSomewhat different', 'TBranch', 'ICorPM',
       'WorkExp', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8',
       'Frequency_1', 'Frequency_2', 'Frequency_3', 'TimeSearching',
       'TimeAnswering', 'ProfessionalTech', 'Industry', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [10]:
df_2024.columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
       'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
       'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=114)

In [11]:
df_2025.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [12]:
df_2022.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73268 entries, 0 to 73267
Data columns (total 79 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ResponseId                      73268 non-null  int64
 1   MainBranch                      73268 non-null  object
 2   Employment                      71709 non-null  object
 3   RemoteWork                      58958 non-null  object
 4   CodingActivities                58899 non-null  object
 5   EdLevel                         71571 non-null  object
 6   LearnCode                       71580 non-null  object
 7   LearnCodeOnline                 50685 non-null  object
 8   LearnCodeCoursesCert            29389 non-null  object
 9   YearsCode                       71331 non-null  object
 10  YearsCodePro                    51833 non-null  object
 11  DevType                         61302 non-null  object
 12  OrgSize                         51039 non-null  object
 13  PurchaseInfluence               50969 non-null  object
 14  BuyNewTool                      67963 non-null  object
 15  Country                         71771 non-null  object
 16  Currency                        51264 non-null  object
 17  CompTotal                       38422 non-null  float64
 18  CompFreq                        44425 non-null  object
 19  LanguageHaveWorkedWith          70975 non-null  object
 20  LanguageWantToWorkWith          67027 non-null  object
 21  DatabaseHaveWorkedWith          60121 non-null  object
 22  DatabaseWantToWorkWith          51014 non-null  object
 23  PlatformHaveWorkedWith          49924 non-null  object
 24  PlatformWantToWorkWith          40415 non-null  object
 25  WebframeHaveWorkedWith          53544 non-null  object
 26  WebframeWantToWorkWith          46122 non-null  object
 27  MiscTechHaveWorkedWith          44992 non-null  object
 28  MiscTechWantToWorkWith          36810 non-null  object
 29  ToolsTechHaveWorkedWith         54171 non-null  object
 30  ToolsTechWantToWorkWith         46566 non-null  object
 31  NEWCollabToolsHaveWorkedWith    70347 non-null  object
 32  NEWCollabToolsWantToWorkWith    64108 non-null  object
 33  OpSysProfessional use           65503 non-null  object
 34  OpSysPersonal use               70963 non-null  object
 35  VersionControlSystem            71379 non-null  object
 36  VCInteraction                   68156 non-null  object
 37  VCHostingPersonal use           0 non-null      float64
 38  VCHostingProfessional use       0 non-null      float64
 39  OfficeStackAsyncHaveWorkedWith  46223 non-null  object
 40  OfficeStackAsyncWantToWorkWith  32072 non-null  object
 41  OfficeStackSyncHaveWorkedWith   62128 non-null  object
 42  OfficeStackSyncWantToWorkWith   47688 non-null  object
 43  Blockchain                      71071 non-null  object
 44  NEWSOSites                      71365 non-null  object
 45  SOVisitFreq                     70961 non-null  object
 46  SOAccount                       71572 non-null  object
 47  SOPartFreq                      58229 non-null  object
 48  SOComm                          71408 non-null  object
 49  Age                             70946 non-null  object
 50  Gender                          70853 non-null  object
 51  Trans                           70315 non-null  object
 52  Sexuality                       66565 non-null  object
 53  Ethnicity                       69474 non-null  object
 54  Accessibility                   67244 non-null  object
 55  MentalHealth                    66447 non-null  object
 56  TBranch                         52670 non-null  object
 57  ICorPM                          36283 non-null  object
 58  WorkExp                         36769 non-null  float64
 59  Knowledge_1                     35804 non-null  object
 60  Knowledge_2                     34973 non-null  object
 61  Knowledge_3                     35133 non-null  object
 62  Knowledge_4                     35097 non-null  object
 63  Knowledge_5                     35014 non-null  object
 64  Knowledge_6                     34991 non-null  object
 65  Knowledge_7                     34977 non-null  object
 66  Frequency_1                     35371 non-null  object
 67  Frequency_2                     35344 non-null  object
 68  Frequency_3                     34515 non-null  object
 69  TimeSearching                   36198 non-null  object
 70  TimeAnswering                   36022 non-null  object
 71  Onboarding                      35679 non-null  object
 72  ProfessionalTech                34906 non-null  object
 73  TrueFalse_1                     35819 non-null  object
 74  TrueFalse_2                     35715 non-null  object
 75  TrueFalse_3                     35749 non-null  object
 76  SurveyLength                    70444 non-null  object
 77  SurveyEase                      70508 non-null  object
 78  ConvertedCompYearly             38071 non-null  float64
dtypes: float64(5), int64(1), object(73)
memory usage: 44.2+ MB

In [13]:
df_2023.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89184 entries, 0 to 89183
Data columns (total 84 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ResponseId                           89184 non-null  int64
 1   Q120                                 89184 non-null  object
 2   MainBranch                           89184 non-null  object
 3   Age                                  89184 non-null  object
 4   Employment                           87898 non-null  object
 5   RemoteWork                           73810 non-null  object
 6   CodingActivities                     73764 non-null  object
 7   EdLevel                              87973 non-null  object
 8   LearnCode                            87663 non-null  object
 9   LearnCodeOnline                      70084 non-null  object
 10  LearnCodeCoursesCert                 37076 non-null  object
 11  YearsCode                            87435 non-null  object
 12  YearsCodePro                         66136 non-null  object
 13  DevType                              76872 non-null  object
 14  OrgSize                              65043 non-null  object
 15  PurchaseInfluence                    64964 non-null  object
 16  TechList                             60851 non-null  object
 17  BuyNewTool                           83009 non-null  object
 18  Country                              87973 non-null  object
 19  Currency                             65334 non-null  object
 20  CompTotal                            48225 non-null  float64
 21  LanguageHaveWorkedWith               87140 non-null  object
 22  LanguageWantToWorkWith               80709 non-null  object
 23  DatabaseHaveWorkedWith               73435 non-null  object
 24  DatabaseWantToWorkWith               60911 non-null  object
 25  PlatformHaveWorkedWith               63628 non-null  object
 26  PlatformWantToWorkWith               51308 non-null  object
 27  WebframeHaveWorkedWith               66938 non-null  object
 28  WebframeWantToWorkWith               56741 non-null  object
 29  MiscTechHaveWorkedWith               57019 non-null  object
 30  MiscTechWantToWorkWith               46848 non-null  object
 31  ToolsTechHaveWorkedWith              77884 non-null  object
 32  ToolsTechWantToWorkWith              68315 non-null  object
 33  NEWCollabToolsHaveWorkedWith         85864 non-null  object
 34  NEWCollabToolsWantToWorkWith         76649 non-null  object
 35  OpSysPersonal use                    86557 non-null  object
 36  OpSysProfessional use                78587 non-null  object
 37  OfficeStackAsyncHaveWorkedWith       69090 non-null  object
 38  OfficeStackAsyncWantToWorkWith       53743 non-null  object
 39  OfficeStackSyncHaveWorkedWith        83439 non-null  object
 40  OfficeStackSyncWantToWorkWith        69776 non-null  object
 41  AISearchHaveWorkedWith               56328 non-null  object
 42  AISearchWantToWorkWith               46150 non-null  object
 43  AIDevHaveWorkedWith                  25904 non-null  object
 44  AIDevWantToWorkWith                  19587 non-null  object
 45  NEWSOSites                           87973 non-null  object
 46  SOVisitFreq                          87140 non-null  object
 47  SOAccount                            87852 non-null  object
 48  SOPartFreq                           66061 non-null  object
 49  SOComm                               87692 non-null  object
 50  SOAI                                 47858 non-null  object
 51  AISelect                             87973 non-null  object
 52  AISent                               61501 non-null  object
 53  AIAcc                                38594 non-null  object
 54  AIBen                                61396 non-null  object
 55  AIToolInterested in Using            32783 non-null  object
 56  AIToolCurrently Using                36137 non-null  object
 57  AIToolNot interested in Using        21069 non-null  object
 58  AINextVery different                 12661 non-null  object
 59  AINextNeither different nor similar  6599 non-null   object
 60  AINextSomewhat similar               6238 non-null   object
 61  AINextVery similar                   2621 non-null   object
 62  AINextSomewhat different             23303 non-null  object
 63  TBranch                              65768 non-null  object
 64  ICorPM                               43668 non-null  object
 65  WorkExp                              43579 non-null  float64
 66  Knowledge_1                          42535 non-null  object
 67  Knowledge_2                          41670 non-null  object
 68  Knowledge_3                          41798 non-null  object
 69  Knowledge_4                          41684 non-null  object
 70  Knowledge_5                          41527 non-null  object
 71  Knowledge_6                          41520 non-null  object
 72  Knowledge_7                          41467 non-null  object
 73  Knowledge_8                          41404 non-null  object
 74  Frequency_1                          41916 non-null  object
 75  Frequency_2                          41925 non-null  object
 76  Frequency_3                          41054 non-null  object
 77  TimeSearching                        42778 non-null  object
 78  TimeAnswering                        42629 non-null  object
 79  ProfessionalTech                     41783 non-null  object
 80  Industry                             36774 non-null  object
 81  SurveyLength                         86485 non-null  object
 82  SurveyEase                           86554 non-null  object
 83  ConvertedCompYearly                  48019 non-null  float64
dtypes: float64(3), int64(1), object(80)
memory usage: 57.2+ MB

In [14]:
df_2024.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Data columns (total 114 columns):
 #    Column                          Non-Null Count  Dtype
---   ------                          --------------  -----
 0    ResponseId                      65437 non-null  int64
 1    MainBranch                      65437 non-null  object
 2    Age                             65437 non-null  object
 3    Employment                      65437 non-null  object
 4    RemoteWork                      54806 non-null  object
 5    Check                           65437 non-null  object
 6    CodingActivities                54466 non-null  object
 7    EdLevel                         60784 non-null  object
 8    LearnCode                       60488 non-null  object
 9    LearnCodeOnline                 49237 non-null  object
 10   TechDoc                         40897 non-null  object
 11   YearsCode                       59869 non-null  object
 12   YearsCodePro                    51610 non-null  object
 13   DevType                         59445 non-null  object
 14   OrgSize                         47480 non-null  object
 15   PurchaseInfluence               47406 non-null  object
 16   BuyNewTool                      45181 non-null  object
 17   BuildvsBuy                      43358 non-null  object
 18   TechEndorse                     43668 non-null  object
 19   Country                         58930 non-null  object
 20   Currency                        46684 non-null  object
 21   CompTotal                       33740 non-null  float64
 22   LanguageHaveWorkedWith          59745 non-null  object
 23   LanguageWantToWorkWith          55752 non-null  object
 24   LanguageAdmired                 50872 non-null  object
 25   DatabaseHaveWorkedWith          50254 non-null  object
 26   DatabaseWantToWorkWith          42558 non-null  object
 27   DatabaseAdmired                 38557 non-null  object
 28   PlatformHaveWorkedWith          42366 non-null  object
 29   PlatformWantToWorkWith          34532 non-null  object
 30   PlatformAdmired                 31377 non-null  object
 31   WebframeHaveWorkedWith          45161 non-null  object
 32   WebframeWantToWorkWith          38535 non-null  object
 33   WebframeAdmired                 34943 non-null  object
 34   EmbeddedHaveWorkedWith          22214 non-null  object
 35   EmbeddedWantToWorkWith          17600 non-null  object
 36   EmbeddedAdmired                 16733 non-null  object
 37   MiscTechHaveWorkedWith          39443 non-null  object
 38   MiscTechWantToWorkWith          32964 non-null  object
 39   MiscTechAdmired                 29596 non-null  object
 40   ToolsTechHaveWorkedWith         52482 non-null  object
 41   ToolsTechWantToWorkWith         46084 non-null  object
 42   ToolsTechAdmired                43997 non-null  object
 43   NEWCollabToolsHaveWorkedWith    57592 non-null  object
 44   NEWCollabToolsWantToWorkWith    52087 non-null  object
 45   NEWCollabToolsAdmired           50711 non-null  object
 46   OpSysPersonal use               58174 non-null  object
 47   OpSysProfessional use           52973 non-null  object
 48   OfficeStackAsyncHaveWorkedWith  48093 non-null  object
 49   OfficeStackAsyncWantToWorkWith  38966 non-null  object
 50   OfficeStackAsyncAdmired         37204 non-null  object
 51   OfficeStackSyncHaveWorkedWith   55545 non-null  object
 52   OfficeStackSyncWantToWorkWith   46711 non-null  object
 53   OfficeStackSyncAdmired          44712 non-null  object
 54   AISearchDevHaveWorkedWith       44453 non-null  object
 55   AISearchDevWantToWorkWith       36701 non-null  object
 56   AISearchDevAdmired              35543 non-null  object
 57   NEWSOSites                      60286 non-null  object
 58   SOVisitFreq                     59536 non-null  object
 59   SOAccount                       59560 non-null  object
 60   SOPartFreq                      45237 non-null  object
 61   SOHow                           58962 non-null  object
 62   SOComm                          59163 non-null  object
 63   AISelect                        60907 non-null  object
 64   AISent                          45873 non-null  object
 65   AIBen                           36894 non-null  object
 66   AIAcc                           37302 non-null  object
 67   AIComplex                       37021 non-null  object
 68   AIToolCurrently Using           35072 non-null  object
 69   AIToolInterested in Using       30691 non-null  object
 70   AIToolNot interested in Using   24414 non-null  object
 71   AINextMuch more integrated      13438 non-null  object
 72   AINextNo change                 12498 non-null  object
 73   AINextMore integrated           24428 non-null  object
 74   AINextLess integrated           2355 non-null   object
 75   AINextMuch less integrated      1148 non-null   object
 76   AIThreat                        44689 non-null  object
 77   AIEthics                        41548 non-null  object
 78   AIChallenges                    37531 non-null  object
 79   TBranch                         44477 non-null  object
 80   ICorPM                          29801 non-null  object
 81   WorkExp                         29658 non-null  float64
 82   Knowledge_1                     28664 non-null  object
 83   Knowledge_2                     28021 non-null  object
 84   Knowledge_3                     28095 non-null  object
 85   Knowledge_4                     28030 non-null  object
 86   Knowledge_5                     27880 non-null  object
 87   Knowledge_6                     27864 non-null  object
 88   Knowledge_7                     27778 non-null  object
 89   Knowledge_8                     27758 non-null  object
 90   Knowledge_9                     27635 non-null  object
 91   Frequency_1                     28369 non-null  object
 92   Frequency_2                     28364 non-null  object
 93   Frequency_3                     27710 non-null  object
 94   TimeSearching                   28911 non-null  object
 95   TimeAnswering                   28844 non-null  object
 96   Frustration                     28251 non-null  object
 97   ProfessionalTech                27764 non-null  object
 98   ProfessionalCloud               28491 non-null  object
 99   ProfessionalQuestion            28807 non-null  object
 100  Industry                        28858 non-null  object
 101  JobSatPoints_1                  29324 non-null  float64
 102  JobSatPoints_4                  29393 non-null  float64
 103  JobSatPoints_5                  29411 non-null  float64
 104  JobSatPoints_6                  29450 non-null  float64
 105  JobSatPoints_7                  29448 non-null  float64
 106  JobSatPoints_8                  29456 non-null  float64
 107  JobSatPoints_9                  29456 non-null  float64
 108  JobSatPoints_10                 29450 non-null  float64
 109  JobSatPoints_11                 29445 non-null  float64
 110  SurveyLength                    56182 non-null  object
 111  SurveyEase                      56238 non-null  object
 112  ConvertedCompYearly             23435 non-null  float64
 113  JobSat                          29126 non-null  float64
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

In [15]:
df_2025.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Data columns (total 172 columns):
 #    Column                                    Non-Null Count  Dtype
---   ------                                    --------------  -----
 0    ResponseId                                49191 non-null  int64
 1    MainBranch                                49191 non-null  object
 2    Age                                       49191 non-null  object
 3    EdLevel                                   48149 non-null  object
 4    Employment                                48339 non-null  object
 5    EmploymentAddl                            44875 non-null  object
 6    WorkExp                                   42893 non-null  float64
 7    LearnCodeChoose                           46858 non-null  object
 8    LearnCode                                 33556 non-null  object
 9    LearnCodeAI                               45201 non-null  object
 10   AILearnHow                                28257 non-null  object
 11   YearsCode                                 43042 non-null  float64
 12   DevType                                   43680 non-null  object
 13   OrgSize                                   34178 non-null  object
 14   ICorPM                                    33243 non-null  object
 15   RemoteWork                                33780 non-null  object
 16   PurchaseInfluence                         37437 non-null  object
 17   TechEndorseIntro                          37556 non-null  object
 18   TechEndorse_1                             35975 non-null  float64
 19   TechEndorse_2                             35975 non-null  float64
 20   TechEndorse_3                             35975 non-null  float64
 21   TechEndorse_4                             35975 non-null  float64
 22   TechEndorse_5                             35975 non-null  float64
 23   TechEndorse_6                             35975 non-null  float64
 24   TechEndorse_7                             35975 non-null  float64
 25   TechEndorse_8                             35975 non-null  float64
 26   TechEndorse_9                             35975 non-null  float64
 27   TechEndorse_13                            35975 non-null  float64
 28   TechEndorse_13_TEXT                       2009 non-null   object
 29   TechOppose_1                              34259 non-null  float64
 30   TechOppose_2                              34259 non-null  float64
 31   TechOppose_3                              34259 non-null  float64
 32   TechOppose_5                              34259 non-null  float64
 33   TechOppose_7                              34259 non-null  float64
 34   TechOppose_9                              34259 non-null  float64
 35   TechOppose_11                             34259 non-null  float64
 36   TechOppose_13                             34259 non-null  float64
 37   TechOppose_16                             34259 non-null  float64
 38   TechOppose_15                             34259 non-null  float64
 39   TechOppose_15_TEXT                        1647 non-null   object
 40   Industry                                  33642 non-null  object
 41   JobSatPoints_1                            24943 non-null  float64
 42   JobSatPoints_2                            24943 non-null  float64
 43   JobSatPoints_3                            24943 non-null  float64
 44   JobSatPoints_4                            24943 non-null  float64
 45   JobSatPoints_5                            24943 non-null  float64
 46   JobSatPoints_6                            24943 non-null  float64
 47   JobSatPoints_7                            24943 non-null  float64
 48   JobSatPoints_8                            24943 non-null  float64
 49   JobSatPoints_9                            24943 non-null  float64
 50   JobSatPoints_10                           24943 non-null  float64
 51   JobSatPoints_11                           24943 non-null  float64
 52   JobSatPoints_13                           24943 non-null  float64
 53   JobSatPoints_14                           24943 non-null  float64
 54   JobSatPoints_15                           24943 non-null  float64
 55   JobSatPoints_16                           24943 non-null  float64
 56   JobSatPoints_15_TEXT                      664 non-null    object
 57   AIThreat                                  36078 non-null  object
 58   NewRole                                   35527 non-null  object
 59   ToolCountWork                             27611 non-null  float64
 60   ToolCountPersonal                         25582 non-null  float64
 61   Country                                   35437 non-null  object
 62   Currency                                  35437 non-null  object
 63   CompTotal                                 24866 non-null  float64
 64   LanguageChoice                            32214 non-null  object
 65   LanguageHaveWorkedWith                    31671 non-null  object
 66   LanguageWantToWorkWith                    27079 non-null  object
 67   LanguageAdmired                           23470 non-null  object
 68   LanguagesHaveEntry                        3982 non-null   object
 69   LanguagesWantEntry                        3150 non-null   object
 70   DatabaseChoice                            31688 non-null  object
 71   DatabaseHaveWorkedWith                    25550 non-null  object
 72   DatabaseWantToWorkWith                    19733 non-null  object
 73   DatabaseAdmired                           17295 non-null  object
 74   DatabaseHaveEntry                         2150 non-null   object
 75   DatabaseWantEntry                         1533 non-null   object
 76   PlatformChoice                            31262 non-null  object
 77   PlatformHaveWorkedWith                    24258 non-null  object
 78   PlatformWantToWorkWith                    19415 non-null  object
 79   PlatformAdmired                           17822 non-null  object
 80   PlatformHaveEntry                         3957 non-null   object
 81   PlatformWantEntry                         3100 non-null   object
 82   WebframeChoice                            31193 non-null  object
 83   WebframeHaveWorkedWith                    22992 non-null  object
 84   WebframeWantToWorkWith                    17639 non-null  object
 85   WebframeAdmired                           15709 non-null  object
 86   WebframeHaveEntry                         3294 non-null   object
 87   WebframeWantEntry                         2630 non-null   object
 88   DevEnvsChoice                             31079 non-null  object
 89   DevEnvsHaveWorkedWith                     26019 non-null  object
 90   DevEnvsWantToWorkWith                     20614 non-null  object
 91   DevEnvsAdmired                            19492 non-null  object
 92   DevEnvHaveEntry                           2762 non-null   object
 93   DevEnvWantEntry                           2112 non-null   object
 94   SOTagsHaveWorkedWith                      17922 non-null  object
 95   SOTagsWantToWorkWith                      13587 non-null  object
 96   SOTagsAdmired                             12240 non-null  object
 97   SOTagsHaveEntry                           458 non-null    object
 98   SOTagsWant Entry                          430 non-null    object
 99   OpSysPersonal use                         31417 non-null  object
 100  OpSysProfessional use                     28883 non-null  object
 101  OfficeStackAsyncHaveWorkedWith            29858 non-null  object
 102  OfficeStackAsyncWantToWorkWith            23206 non-null  object
 103  OfficeStackAsyncAdmired                   22208 non-null  object
 104  OfficeStackHaveEntry                      2589 non-null   object
 105  OfficeStackWantEntry                      1617 non-null   object
 106  CommPlatformHaveWorkedWith                30065 non-null  object
 107  CommPlatformWantToWorkWith                23351 non-null  object
 108  CommPlatformAdmired                       22877 non-null  object
 109  CommPlatformHaveEntr                      1476 non-null   object
 110  CommPlatformWantEntr                      1184 non-null   object
 111  AIModelsChoice                            30239 non-null  object
 112  AIModelsHaveWorkedWith                    16281 non-null  object
 113  AIModelsWantToWorkWith                    11845 non-null  object
 114  AIModelsAdmired                           11284 non-null  object
 115  AIModelsHaveEntry                         776 non-null    object
 116  AIModelsWantEntry                         475 non-null    object
 117  SOAccount                                 32797 non-null  object
 118  SOVisitFreq                               32710 non-null  object
 119  SODuration                                32627 non-null  object
 120  SOPartFreq                                32228 non-null  object
 121  SO_Dev_Content                            22836 non-null  object
 122  SO_Actions_1                              26260 non-null  float64
 123  SO_Actions_16                             24340 non-null  float64
 124  SO_Actions_3                              26260 non-null  float64
 125  SO_Actions_4                              26260 non-null  float64
 126  SO_Actions_5                              26260 non-null  float64
 127  SO_Actions_6                              26260 non-null  float64
 128  SO_Actions_9                              26260 non-null  float64
 129  SO_Actions_7                              26260 non-null  float64
 130  SO_Actions_10                             26260 non-null  float64
 131  SO_Actions_15                             26260 non-null  float64
 132  SO_Actions_15_TEXT                        823 non-null    object
 133  SOComm                                    31706 non-null  object
 134  SOFriction                                30787 non-null  object
 135  AISelect                                  33720 non-null  object
 136  AISent                                    33467 non-null  object
 137  AIAcc                                     33297 non-null  object
 138  AIComplex                                 33283 non-null  object
 139  AIToolCurrently partially AI              21028 non-null  object
 140  AIToolDon't plan to use AI for this task  25381 non-null  object
 141  AIToolPlan to partially use AI            22556 non-null  object
 142  AIToolPlan to mostly use AI               12818 non-null  object
 143  AIToolCurrently mostly AI                 11225 non-null  object
 144  AIFrustration                             31522 non-null  object
 145  AIExplain                                 26586 non-null  object
 146  AIAgents                                  31919 non-null  object
 147  AIAgentChange                             31678 non-null  object
 148  AIAgent_Uses                              12320 non-null  object
 149  AgentUsesGeneral                          5805 non-null   object
 150  AIAgentImpactSomewhat agree               10146 non-null  object
 151  AIAgentImpactNeutral                      9675 non-null   object
 152  AIAgentImpactSomewhat disagree            5791 non-null   object
 153  AIAgentImpactStrongly agree               6687 non-null   object
 154  AIAgentImpactStrongly disagree            3779 non-null   object
 155  AIAgentChallengesNeutral                  21295 non-null  object
 156  AIAgentChallengesSomewhat disagree        12125 non-null  object
 157  AIAgentChallengesStrongly agree           23108 non-null  object
 158  AIAgentChallengesSomewhat agree           21947 non-null  object
 159  AIAgentChallengesStrongly disagree        9314 non-null   object
 160  AIAgentKnowledge                          3401 non-null   object
 161  AIAgentKnowWrite                          766 non-null    object
 162  AIAgentOrchestration                      3760 non-null   object
 163  AIAgentOrchWrite                          478 non-null    object
 164  AIAgentObserveSecure                      2692 non-null   object
 165  AIAgentObsWrite                           264 non-null    object
 166  AIAgentExternal                           8332 non-null   object
 167  AIAgentExtWrite                           859 non-null    object
 168  AIHuman                                   29194 non-null  object
 169  AIOpen                                    22540 non-null  object
 170  ConvertedCompYearly                       23947 non-null  float64
 171  JobSat                                    26670 non-null  float64
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [16]:
cols_2022 = set(df_2022.columns)

In [17]:
cols_2023 = set(df_2023.columns)

In [18]:
cols_2024 = set(df_2024.columns)

In [19]:
cols_2025 = set(df_2025.columns)

In [20]:
common_cols = (cols_2022) & (cols_2023) & (cols_2024) & (cols_2025)
common_cols

{'Age',
 'CompTotal',
 'ConvertedCompYearly',
 'Country',
 'Currency',
 'DatabaseHaveWorkedWith',
 'DatabaseWantToWorkWith',
 'DevType',
 'EdLevel',
 'Employment',
 'ICorPM',
 'LanguageHaveWorkedWith',
 'LanguageWantToWorkWith',
 'LearnCode',
 'MainBranch',
 'OfficeStackAsyncHaveWorkedWith',
 'OfficeStackAsyncWantToWorkWith',
 'OpSysPersonal use',
 'OpSysProfessional use',
 'OrgSize',
 'PlatformHaveWorkedWith',
 'PlatformWantToWorkWith',
 'PurchaseInfluence',
 'RemoteWork',
 'ResponseId',
 'SOAccount',
 'SOComm',
 'SOPartFreq',
 'SOVisitFreq',
 'WebframeHaveWorkedWith',
 'WebframeWantToWorkWith',
 'WorkExp',
 'YearsCode'}

In [21]:
print(len(common_cols))

33

In [22]:
cols = sorted(common_cols)
print(cols)

['Age', 'CompTotal', 'ConvertedCompYearly', 'Country', 'Currency', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DevType', 'EdLevel', 'Employment', 'ICorPM', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LearnCode', 'MainBranch', 'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OpSysPersonal use', 'OpSysProfessional use', 'OrgSize', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PurchaseInfluence', 'RemoteWork', 'ResponseId', 'SOAccount', 'SOComm', 'SOPartFreq', 'SOVisitFreq', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'WorkExp', 'YearsCode']

## Columns common to all four years (2022–2025)

33 columns exist in every survey year. Short explanation of each:

### Identification & filtering
| Column | Meaning | Note |
|---|---|---|
| `ResponseId` | ID number of each respondent | Only unique *within* one year, not across years |
| `MainBranch` | Relation to coding (e.g. developer by profession, learning to code, hobby) | Useful for filtering professional developers |
| `Employment` | Employment status (full-time, part-time, freelancer, student, …) | Can contain several answers separated by `;` – categories changed in 2025 |

### Target
| Column | Meaning | Note |
|---|---|---|
| `ConvertedCompYearly` | Total yearly compensation, converted to US dollars | **Target variable** |
| `CompTotal` | Compensation as entered, in the respondent's own currency | Not comparable across countries – would leak the target |
| `Currency` | Currency used for `CompTotal` | Only describes `CompTotal` – would leak the target |

### Person
| Column | Meaning | Note |
|---|---|---|
| `Age` | Age group (e.g. "25-34 years old") | Categories, not exact numbers |
| `Country` | Country of residence | Many categories – rare countries may need grouping |
| `EdLevel` | Highest level of formal education | Long text labels |
| `LearnCode` | How the person learned to code (books, online, school, …) | Multi-select (`;`-separated) |

### Experience
| Column | Meaning | Note |
|---|---|---|
| `YearsCode` | Years of coding in total (including education) | Text values like "Less than 1 year" in 2022–2024; numeric in 2025 |
| `WorkExp` | Years of professional work experience | Numeric |

### Job
| Column | Meaning | Note |
|---|---|---|
| `DevType` | Job role (e.g. back-end developer, data scientist) | Can contain several roles in some years |
| `OrgSize` | Size of the company (number of employees) | Categories |
| `ICorPM` | Individual contributor or people manager | Two categories |
| `RemoteWork` | Work arrangement: remote, hybrid or in-person | Labels differ between years (e.g. "Fully remote" vs "Remote") |
| `PurchaseInfluence` | How much influence the person has on technology purchases at work | Categories |

### Technology (all multi-select, `;`-separated)
| Column | Meaning |
|---|---|
| `LanguageHaveWorkedWith` | Programming languages used in the past year |
| `LanguageWantToWorkWith` | Programming languages the person wants to use next year |
| `DatabaseHaveWorkedWith` | Databases used |
| `DatabaseWantToWorkWith` | Databases the person wants to use |
| `PlatformHaveWorkedWith` | Cloud platforms used (AWS, Azure, …) |
| `PlatformWantToWorkWith` | Cloud platforms the person wants to use |
| `WebframeHaveWorkedWith` | Web frameworks used (React, Django, …) |
| `WebframeWantToWorkWith` | Web frameworks the person wants to use |
| `OfficeStackAsyncHaveWorkedWith` | Asynchronous collaboration tools used (Jira, Confluence, …) |
| `OfficeStackAsyncWantToWorkWith` | Asynchronous collaboration tools the person wants to use |
| `OpSysPersonal use` | Operating systems used privately |
| `OpSysProfessional use` | Operating systems used at work |

### Stack Overflow usage
| Column | Meaning |
|---|---|
| `SOAccount` | Whether the person has a Stack Overflow account |
| `SOVisitFreq` | How often they visit Stack Overflow |
| `SOPartFreq` | How often they participate (ask/answer) |
| `SOComm` | Whether they feel part of the Stack Overflow community |

### Observations
- `YearsCodePro` (years of professional coding) exists in 2022–2024 but **not in 2025** → `WorkExp` is the common experience column.
- Several columns have **different answer categories** in different years (e.g. `RemoteWork`, `Employment`) → they need harmonising before combining the years.

**Finding Null/NA values**

In [23]:
na_2022 = df_2022[list(common_cols)].isna().mean()*100

In [24]:
na_2023 = df_2023[list(common_cols)].isna().mean()*100

In [25]:
na_2024 = df_2024[list(common_cols)].isna().mean()*100

In [26]:
na_2025 = df_2025[list(common_cols)].isna().mean()*100

In [27]:
na_tabel = pd.DataFrame({"2022": na_2022, "2023":na_2023, "2024":na_2024, "2025":na_2025})
na_tabel.round(1).sort_values(by="2025", ascending = False)

                                2022  2023  2024  2025
WebframeWantToWorkWith          37.1  36.4  41.1  64.1
PlatformWantToWorkWith          44.8  42.5  47.2  60.5
DatabaseWantToWorkWith          30.4  31.7  35.0  59.9
WebframeHaveWorkedWith          26.9  24.9  31.0  53.3
OfficeStackAsyncWantToWorkWith  56.2  39.7  40.5  52.8
ConvertedCompYearly             48.0  46.2  64.2  51.3
PlatformHaveWorkedWith          31.9  28.7  35.3  50.7
CompTotal                       47.6  45.9  48.4  49.5
DatabaseHaveWorkedWith          17.9  17.7  23.2  48.1
LanguageWantToWorkWith           8.5   9.5  14.8  45.0
OpSysProfessional use           10.6  11.9  19.0  41.3
OfficeStackAsyncHaveWorkedWith  36.9  22.5  26.5  39.3
OpSysPersonal use                3.1   2.9  11.1  36.1
LanguageHaveWorkedWith           3.1   2.3   8.7  35.6
SOComm                           2.5   1.7   9.6  35.5
SOPartFreq                      20.5  25.9  30.9  34.5
SOVisitFreq                      3.1   2.3   9.0  33.5
SOAccount                        2.3   1.5   9.0  33.3
ICorPM                          50.5  51.0  54.5  32.4
LearnCode                        2.3   1.7   7.6  31.8
RemoteWork                      19.5  17.2  16.2  31.3
OrgSize                         30.3  27.1  27.4  30.5
Currency                        30.0  26.7  28.7  28.0
Country                          2.0   1.4   9.9  28.0
PurchaseInfluence               30.4  27.2  27.6  23.9
WorkExp                         49.8  51.1  54.7  12.8
YearsCode                        2.6   2.0   8.5  12.5
DevType                         16.3  13.8   9.2  11.2
EdLevel                          2.3   1.4   7.1   2.1
Employment                       2.1   1.4   0.0   1.7
ResponseId                       0.0   0.0   0.0   0.0
Age                              3.2   0.0   0.0   0.0
MainBranch                       0.0   0.0   0.0   0.0

### Observations on missing values

- **Salary (`ConvertedCompYearly`) is missing for about half of the respondents** (46–51% in 2022, 2023 and 2025, and 64% in 2024). These rows cannot be used for salary analysis, so they should be removed first. After that, the missing values of the other columns should be checked again.
- **`WorkExp` and `ICorPM` are about 50% empty in 2022–2024, but much less in 2025** (13% and 32%). In the earlier surveys these questions were part of a later section that only about half of the people answered. In 2025, `WorkExp` was asked at the beginning of the survey.
- **In 2025, basic columns have many more missing values than before**, for example `Country` (28% vs. about 2% in 2022) and `LanguageHaveWorkedWith` (36% vs. about 3%). The 2025 survey was much longer (172 columns), so many people probably stopped answering halfway.
- **Empty technology columns** (e.g. `PlatformHaveWorkedWith`) can mean either "skipped the question" or "does not use this technology", which matters when interpreting them.
- **In 2024, about 10,000 people have `CompTotal` but no `ConvertedCompYearly`**, which means their salary was not converted. This should be checked during salary cleaning.

**Combine DSs and Adding year columns**

In [28]:
small_2022 = df_2022[cols].copy()
small_2022["Year"] = 2022

small_2023 = df_2023[cols].copy()
small_2023["Year"] = 2023

small_2024 = df_2024[cols].copy()
small_2024["Year"] = 2024

small_2025 = df_2025[cols].copy()
small_2025["Year"] = 2025

In [29]:
Combined = pd.concat([small_2022, small_2023, small_2024, small_2025], ignore_index = True)

In [30]:
Combined.shape

(277080, 34)

In [31]:
Combined

,Age,CompTotal,ConvertedCompYearly,Country,Currency,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DevType,EdLevel,Employment,...,ResponseId,SOAccount,SOComm,SOPartFreq,SOVisitFreq,WebframeHaveWorkedWith,WebframeWantToWorkWith,WorkExp,YearsCode,Year
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
1,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,NaN,NaN,"Employed, full-time",...,2,Yes,Not sure,Daily or almost daily,Daily or almost daily,NaN,NaN,NaN,NaN,2022
2,25-34 years old,32000.0,40205.0,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,Microsoft SQL Server,Microsoft SQL Server,Data scientist or machine learning specialist;...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Employed, full-time",...,3,Yes,Neutral,Multiple times per day,Multiple times per day,Angular.js,Angular;Angular.js,NaN,14,2022
3,35-44 years old,60000.0,215232.0,Israel,ILS\tIsraeli new shekel,Microsoft SQL Server,Microsoft SQL Server,"Developer, full-stack","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Employed, full-time",...,4,Yes,"Yes, definitely",A few times per week,Daily or almost daily,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,NaN,20,2022
4,25-34 years old,NaN,NaN,United States of America,USD\tUnited States dollar,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,"Developer, front-end;Developer, full-stack;Dev...","Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Employed, full-time",...,5,Yes,"Yes, definitely",Daily or almost daily,Multiple times per day,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,NaN,8,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277075,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,...,49187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025
277076,45-54 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some college/university study without earning ...,Employed,...,49188,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,2025
277077,35-44 years old,80000.0,NaN,Italy,EUR European Euro,NaN,NaN,"Architect, software or solutions","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,...,49189,NaN,NaN,NaN,NaN,NaN,NaN,17.0,31.0,2025
277078,25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",...,49190,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2025
277079,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,Student,Some college/university study without earning ...,Student,...,49191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2025

In [32]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [33]:
Combined.to_csv('/content/drive/MyDrive/Data_Circle_StackOverflow/combined_2022_2025.csv', index=False)